version: '3.9'

services:

  db:
    build:
        context: db
        dockerfile: Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - explorer_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  explorer_pgdata:
